### Create a new product
POST http://localhost:3000/api/product
Accept: application/json
Content-Type: application/json

{
  "name": "taco",
  "price": 4.99,
  "description": "A Taco"
}


### Get all products
GET http://localhost:3000/api/product
Accept: application/json


### Get product by id
GET http://localhost:3000/api/product/652ae57ff478460b15fb4323
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjUyYjA2MWJiY2RlODk4ZTAwYzkxNThlIiwibmFtZSI6IkFobWVkIEF5bWFuIiwiZW1haWwiOiJ0ZXN0QHRlc3QuY29tIn0sImlhdCI6MTY5NzU1ODMyNiwiZXhwIjoxNjk3NTYxOTI2fQ.tZgTLzMLFwe4UEoOYU3kusj5IVFEg0K-M8isK0m4EvE


### Update product data by id
PATCH http://localhost:3000/api/product/652ae57ff478460b15fb4323
Content-Type: application/json

{
  "price": 2.89
}

### Delete product by id
DELETE http://localhost:3000/api/product/652ae9d0fc681cec1484a350
